// auth
export const USER_LOADED = 'USER_LOADED'
export const USER_LOADING = 'USER_LOADING'
export const ALL_USER_LOADED = 'ALL_USER_LOADED'
export const ALL_USER_LOADING = 'ALL_USER_LOADING'

export const AUTH_REGISTER = 'AUTH_REGISTER'
export const AUTH_LOGIN = 'AUTH_LOGIN'
export const AUTH_ERROR = 'AUTH_ERROR'
export const REGISTER_FAIL = 'REGISTER_FAIL'
export const LOGIN_FAIL = 'LOGIN_FAIL'
export const RESET_STATE = 'RESET_STATE'

export const LOG_OUT = 'LOG_OUT'
export const DELETE_USER = 'DELETE_USER'

export const LOAD_REQUEST = 'LOAD_REQUEST'

export const DELETE_MARKET_REQUEST = 'DELETE_MARKET_REQUEST'
export const FETCH_MARKET = 'FETCH_MARKET'
export const ADD_MARKET = 'ADD_MARKET'
export const DELETE_MARKET = 'DELETE_MARKET'
export const FETCH_MARKET_ERROR = 'FETCH_MARKET_ERROR'
export const ADD_MARKET_ERROR = 'ADD_MARKET_ERROR'
export const DELETE_MARKET_ERROR = 'DELETE_MARKET_ERROR'
export const FETCH_SINGLE_MARKET = 'FETCH_SINGLE_MARKET'
export const FETCH_SINGLE_MARKET_ERROR = 'FETCH_SINGLE_MARKET_ERROR'
export const FILTER_MARKET = 'FILTER_MARKET'

export const CLEAR_ERROR = 'CLEAR_ERROR'
export const ALERT_SUCCESS = 'ALERT_SUCCESS'
export const ALERT_ERROR = 'ALERT_ERROR'
